### ISSUE TITLE
files.upload to be discontinued

### ISSUE THREAD

**Issue by cb-anomitromunshi** [MeilCli/slack-upload-file#1090]
[Please easy english or easy japanese]

## Feature description
hi, i'm using your action extensively , thanks for the action you provided. 
Wanted to confirm if you are planning to upgrade the below mention ask . i received this from Slack.

Hello , We want to remind you about an upcoming date and change to the **files.upload web API** method that affects your UploadApp app on March 11, 2025• 
Support for the files.upload API will be discontinued.

To prepare for this change, we recommend migrating away from **files.upload** and instead using the combination of **files.getUploadURLExternal **and** files.completeUploadExternal**. 
More information on how to use these two APIs together can be found on our Working with files documentation.

**Comment by MeilCli** [comment]
Currently, this action uses filesUploadV2. ref: https://github.com/slackapi/node-slack-sdk/pull/1544
So, I think your concern is no problem.

**Comment by EHJ-52n** [comment]
Following the documentation of [`files.upload`](https://api.slack.com/methods/files.upload#markdown) (I couldn't find any `filesUploadV2` specific API documentation), the need for old applications to update started 8.5.2024 and **this action needs to be updated until 11.03.2025**.
Hence, it is enough time to react.
On the other hand, it might be good to know, that you are working on this, or at least have it on your stack, @MeilCli.

**Comment by MeilCli** [comment]
> I couldn't find any filesUploadV2 specific API documentation

The method isn't api endpoint. Slack node sdk makes convenient method compounding files.getUploadURLExternal and files.completeUploadExternal, and it names filesUploadV2.
So, in my understanding, this action has already migrated to the new file uploading api.

**Comment by EHJ-52n** [comment]
@MeilCli thank you very much for your time and providing the background details.

I just "checked" [the code](https://github.com/MeilCli/slack-upload-file/blob/master/src/main.ts#L89) and the [according documentation](https://tools.slack.dev/node-slack-sdk/reference/web-api/classes/WebClient#filesuploadv2) and post it here for completness.

**Code**

```typescript
[...]
async function postByContent(client: slack.WebClient, option: Option): Promise<slack.FilesUploadResponse> {
    if (option.content == undefined) {
        throw Error(`content is undefined`);
    }
    return await client.filesUploadV2({[...]
```

**Documentation**

> 1. For each file submitted with this method, submit filenames and file metadata to [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) to request a URL to which to send the file data to and an id for the file
> 2. for each returned file upload_url, upload corresponding file to URLs returned from step 1 (e.g. [https://files.slack.com/upload/v1/...\](https://files.slack.com/upload/v1/...%5C)")
> 3. Complete uploads [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal)

From my point of view, this issue can be closed.

@cb-anomitromunshi what do you say?

**Comment by MeilCli** [comment]
close by no response and it may be resolved
