### ISSUE TITLE
Wildcard

### ISSUE THREAD

**Issue by rubycell** [MeilCli/slack-upload-file#447]
Can I use wildcard character in file path? Example: /home/*.txt

**Comment by MeilCli** [comment]
No, this action upload files that exactly matching `file_path`.

Assuming we adopt the glob pattern, do you want to upload all files if there are multiple matches?

**Comment by rubycell** [comment]
Yes, I want to upload all files if there are multiple matches

**Comment by MeilCli** [comment]
@rubycell 
Hi, I now publish v2.
https://github.com/MeilCli/slack-upload-file/releases/tag/v2.0.0

This release include glob pattern support at `file_path`. It means you can upload multiple files.
Would you update your workflow and try it?

**Comment by rubycell** [comment]
Thank you. I used v2.0, but it sent "An HTTP protocol error occurred: statusCode = 408", and uploaded 4 files to Slack, even though only 1 match

**Comment by MeilCli** [comment]
@rubycell Could you tell me about your action usage(`yml`) and file tree of target directory?

**Comment by rubycell** [comment]
I upload a file to Slack for every new commit, the file tree is "build/output/*.apk"

**Comment by MeilCli** [comment]
close because no response
