### ISSUE TITLE
I would like to update a previous upload

### ISSUE THREAD

**Issue by AllanOricil** [MeilCli/slack-upload-file#575]
[Please easy english or easy japanese]

## Feature description

I would like to update a previous upload. Is it possible with Slack APIs? If yes, you could output the unique Id in the actions output. Then add a new action input called "upload-id: string" that when set updates the previous upload.

**Comment by MeilCli** [comment]
@AllanOricil 
https://api.slack.com/methods?filter=files
Slack API cannot edit file, so we should delete and re-upload.
Do you want slack-delete-file action?

**Comment by AllanOricil** [comment]
You could just call the delete api when we configure your action to update an upload

**Comment by MeilCli** [comment]
@AllanOricil 
I published [v2.1.0](https://github.com/MeilCli/slack-upload-file/releases/tag/v2.1.0). This version include `delete_file_id_before_upload` input option and `uploaded_file_id` output.
Those option are simple modification. So, if you want more option, please tell me.

**Comment by AllanOricil** [comment]
@MeilCli you are fast
