### ISSUE TITLE
With large files, issue An HTTP protocol error occurred: statusCode = 408

### ISSUE THREAD

**Issue by sadi304** [MeilCli/slack-upload-file#596]
We are getting 408 with large files, in our use case 150 MB+. 

Some cases its working, some cases they are not being uploaded. I have gone through other issues in this repo similar to this one but couldn't wrap our head properly for a solution.

I saw node sdk supports v2 api now. Also It might be due to some default timeout as well for larger files. Can we get those options here? or get to know some work around to properly upload larger files.

`MeilCli/slack-upload-file@v2`

```
[WARN]  web-api:WebClient:0 files.upload may cause some issues like timeouts for relatively large files.
[INFO]  web-api:WebClient:0 Our latest recommendation is to use client.files.uploadV2() method, which is mostly compatible and much stabler, instead.
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 408
```

**Comment by MeilCli** [comment]
Thanks your issue reporting

Sounds good.
Please wait few time, I plan major update for this.

**Comment by MeilCli** [comment]
@sadi304 
Thanks your information.

I published [v3.0.0](https://github.com/MeilCli/slack-upload-file/releases/tag/v3.0.0).
This action use files.uploadV2 since this version.
So, I add some breaking changes. Please attension.

And, please use that version for confirm your issue resolving.

**Comment by sadi304** [comment]
Hey @MeilCli thanks for the update. We actually removed some matrix from the workflow to decrease the apk counts. So not being able to test it right now, we can close the pr for now. Later we might again integrate back the matrices

**Comment by MeilCli** [comment]
Ok, Thank you!
