### ISSUE TITLE
Error: An API error occurred: missing_scope

### ISSUE THREAD

**Issue by WeiDu2021** [MeilCli/slack-upload-file#614]
[Please easy english or easy japanese]

## Description
The file is sent successfully, but an error will be reported

<img width="955" alt="image" src="https://user-images.githubusercontent.com/77092285/205866675-12ac1e92-6df4-4ad2-9972-79e4bd9a8774.png">

**Comment by MeilCli** [comment]
@WeiDu2021 
Did you add `files:read` scope? 
`files:read` is required since v3.
If you don't want to add `files:read`, you can use v2.

**Comment by WeiDu2021** [comment]
Ok, I will try after modifying, thanks.

**Comment by MeilCli** [comment]
close by no response
