### ISSUE TITLE
links are no longer rendered as links when passed to initial_comment

### ISSUE THREAD

**Issue by AllanOricil** [MeilCli/slack-upload-file#695]
## Description

V2
![image](https://user-images.githubusercontent.com/55927613/228303463-44e53c4f-66de-4e71-a0c4-4eaff512a4bc.png)

V3
![image](https://user-images.githubusercontent.com/55927613/228303516-030e858f-4b60-406f-b537-f2dd355932b3.png)

````yml
initial_comment: "*Workflow:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}|${{ github.workflow }}>\n*Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
````

**Comment by AllanOricil** [comment]
I don't know if it is a slack api issue or a problem with your action.

**Comment by AllanOricil** [comment]
It is a known limitation of v2 
https://github.com/slackapi/node-slack-sdk/issues/1561

**Comment by AllanOricil** [comment]
You could add this information in the README

"Hey, because of slack v2 limitation, v3 might not work for you if your innitial_comment has links in it"

**Comment by MeilCli** [comment]
Thanks your issue reporting.

I wrote its on README.
