### ISSUE TITLE
Upload to slack if file exists or not

### ISSUE THREAD

**Issue by anshuly31** [MeilCli/slack-upload-file#823]
[Please easy english or easy japanese]

## Feature description

Currently if upload file is not present, it fails the github action job
**Expectation:**
Even before we call the upload, Can we add some indicator that first checks if upload file exists or not, and if file does not exist, another option can be provided where we want to raise it as an **error** or **warning** or simple **ignore** this upload.

Something similar to `if-no-files-found` under `actions/upload-artifact@v3`

**Comment by MeilCli** [comment]
Thanks reporting and new idea.

I planned and I will improve feature when I have times.

**Comment by MeilCli** [comment]
Thanks new idea.
I just published [v3.1.0](https://github.com/MeilCli/slack-upload-file/releases/tag/v3.1.0), and it contains this feature.
