### ISSUE TITLE
Action is green, but file is randomly not sent 

### ISSUE THREAD

**Issue by robgutsopedra** [MeilCli/slack-upload-file#828]
Action is ALWAYS green. I'm outputting the permalink: 
```
- name: testing slack upload
   run: 'echo ${{ fromJson(steps.slack_upload_file.outputs.response).files[0].file.permalink }}'
```

![image](https://github.com/MeilCli/slack-upload-file/assets/101654801/21d5bd05-7747-468e-9e26-d903aa5dccb0)

But one out of 5-6 times it's green, but no file is sent to the channel plus clicking the permalink clearly proves it failed (when it works, permalink does work fine)

![image](https://github.com/MeilCli/slack-upload-file/assets/101654801/42d91756-c642-4284-b234-3f36407dd706)

I'd love to know any advices for debugging a bit better, or any ideas are widely appreciated. I've looked at the current issues =(

**Comment by MeilCli** [comment]
close by no response
