### ISSUE TITLE
Need to send 2 files , .txt and .csv 

### ISSUE THREAD

**Issue by cb-anomitromunshi** [MeilCli/slack-upload-file#947]
[Please easy english or easy japanese]
Hi , i want to send 2 files one is .txt and another is .csv. How can i do that?

Also it is okay if we can send the csv to the same thread as reply to the 1st message.

**Comment by MeilCli** [comment]
I think it can send using glob pattern. 
Put the file that you want to send on a directory. And then set directory path with glob pattern
